name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: |
        apt-get update
        apt-get install build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check

